/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sql;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  App classUnderTest = new App();

  @Test
  void appConnection() {
    System.out.println("Connection successful");
    assertTrue(classUnderTest.connect());
  }

  @Test
  void appComboboxes() {
  assertEquals(App.hardwareTypes.size(), App.comboboxes.size());
  assertEquals(App.hardwareList.size(), App.);
  }

}
